management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: health

server:
  shutdown: graceful

spring:
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
  application:
    name: interview-challenge

springdoc:
  writer-with-order-by-keys: true
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs
